export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const STORE_USER = 'STORE_USER'
export const AUTH_USER = 'AUTH_USER'
export const USER_LOADING = 'USER_LOADING'

export const CREATE_OR_UPDATE_USER_REQUEST = 'CREATE_OR_UPDATE_USER_REQUEST'
export const CREATE_OR_UPDATE_USER_SUCCESS = 'CREATE_OR_UPDATE_USER_SUCCESS'
export const CREATE_OR_UPDATE_USER_ERROR = 'CREATE_OR_UPDATE_USER_ERROR'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const SAVE_ACTION_STATE = 'SAVE_ACTION_STATE'

export const SAVE_POST_ID = 'SAVE_POST_ID'

export const SAVE_USER_PREFERENCES_REQUEST = 'SAVE_USER_PREFERENCES_REQUEST'
export const SAVE_USER_PREFERENCES_SUCCESS = 'SAVE_USER_PREFERENCES_SUCCESS'
export const SAVE_USER_PREFERENCES_ERROR = 'SAVE_USER_PREFERENCES_ERROR'

export const UPDATE_USER_PREFERENCES_REQUEST = 'UPDATE_USER_PREFERENCES_REQUEST'
export const UPDATE_USER_PREFERENCES_SUCCESS = 'UPDATE_USER_PREFERENCES_SUCCESS'
export const UPDATE_USER_PREFERENCES_ERROR = 'UPDATE_USER_PREFERENCES_ERROR'

export const GET_USER_PREFERENCES_REQUEST = 'GET_USER_PREFERENCES_REQUEST'
export const GET_USER_PREFERENCES_SUCCESS = 'GET_USER_PREFERENCES_SUCCESS'
export const GET_USER_PREFERENCES_ERROR = 'GET_USER_PREFERENCES_ERROR'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const SAVE_FEEDBACK_REQUEST = 'SAVE_FEEDBACK_REQUEST'
export const SAVE_FEEDBACK_SUCCESS = 'SAVE_FEEDBACK_SUCCESS'
export const SAVE_FEEDBACK_ERROR = 'SAVE_FEEDBACK_ERROR'

export const GET_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST'
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS'
export const GET_FEEDBACKS_ERROR = 'GET_FEEDBACKS_ERROR'

export const GET_POSTS_SUMMARY_REQUEST = 'GET_POSTS_SUMMARY_REQUEST'
export const GET_POSTS_SUMMARY_SUCCESS = 'GET_POSTS_SUMMARY_SUCCESS'
export const GET_POSTS_SUMMARY_ERROR = 'GET_POSTS_SUMMARY_ERROR'

export const GET_INCOMING_POSTS_REQUEST = 'GET_INCOMING_POSTS_REQUEST'
export const GET_INCOMING_POSTS_SUCCESS = 'GET_INCOMING_POSTS_SUCCESS'
export const GET_INCOMING_POSTS_ERROR = 'GET_INCOMING_POSTS_ERROR'

export const GET_OUTGOING_POSTS_REQUEST = 'GET_OUTGOING_POSTS_REQUEST'
export const GET_OUTGOING_POSTS_SUCCESS = 'GET_OUTGOING_POSTS_SUCCESS'
export const GET_OUTGOING_POSTS_ERROR = 'GET_OUTGOING_POSTS_ERROR'

export const GET_NOTIFICATIONS_COUNT_REQUEST = 'GET_NOTIFICATIONS_COUNT_REQUEST'
export const GET_NOTIFICATIONS_COUNT_SUCCESS = 'GET_NOTIFICATIONS_COUNT_SUCCESS'
export const GET_NOTIFICATIONS_COUNT_ERROR = 'GET_NOTIFICATIONS_COUNT_ERROR'

export const CREATE_OR_UPDATE_REACTION_REQUEST =
  'CREATE_OR_UPDATE_REACTION_REQUEST'
export const CREATE_OR_UPDATE_REACTION_SUCCESS =
  'CREATE_OR_UPDATE_REACTION_SUCCESS'
export const CREATE_OR_UPDATE_REACTION_ERROR = 'CREATE_OR_UPDATE_REACTION_ERROR'

export const GET_REACTIONS_REQUEST = 'GET_REACTIONS_REQUEST'
export const GET_REACTIONS_SUCCESS = 'GET_REACTIONS_SUCCESS'
export const GET_REACTIONS_ERROR = 'GET_REACTIONS_ERROR'

export const CREATE_OR_UPDATE_PROFILE_REACTION_REQUEST =
  'CREATE_OR_UPDATE_PROFILE_REACTION_REQUEST'
export const CREATE_OR_UPDATE_PROFILE_REACTION_SUCCESS =
  'CREATE_OR_UPDATE_PROFILE_REACTION_SUCCESS'
export const CREATE_OR_UPDATE_PROFILE_REACTION_ERROR =
  'CREATE_OR_UPDATE_PROFILE_REACTION_ERROR'

export const GET_USER_REACTION_REQUEST = 'GET_USER_REACTION_REQUEST'
export const GET_USER_REACTION_SUCCESS = 'GET_USER_REACTION_SUCCESS'
export const GET_USER_REACTION_ERROR = 'GET_USER_REACTION_ERROR'

export const GET_RECENT_POSTS_REQUEST = 'GET_RECENT_POSTS_REQUEST'
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS'
export const GET_RECENT_POSTS_ERROR = 'GET_RECENT_POSTS_ERROR'

export const GET_POPULAR_POSTS_REQUEST = 'GET_POPULAR_POSTS_REQUEST'
export const GET_POPULAR_POSTS_SUCCESS = 'GET_POPULAR_POSTS_SUCCESS'
export const GET_POPULAR_POSTS_ERROR = 'GET_POPULAR_POSTS_ERROR'

export const GET_REACTIONS_COUNT_REQUEST = 'GET_REACTIONS_COUNT_REQUEST'
export const GET_REACTIONS_COUNT_SUCCESS = 'GET_REACTIONS_COUNT_SUCCESS'
export const GET_REACTIONS_COUNT_ERROR = 'GET_REACTIONS_COUNT_ERROR'

export const CREATE_OR_UPDATE_PROFILE_FOLLOWER_REQUEST =
  'CREATE_OR_UPDATE_PROFILE_FOLLOWER_REQUEST'
export const CREATE_OR_UPDATE_PROFILE_FOLLOWER_SUCCESS =
  'CREATE_OR_UPDATE_PROFILE_FOLLOWER_SUCCESS'
export const CREATE_OR_UPDATE_PROFILE_FOLLOWER_ERROR =
  'CREATE_OR_UPDATE_PROFILE_FOLLOWER_ERROR'

export const GET_USER_FOLLOWER_REQUEST = 'GET_USER_FOLLOWER_REQUEST'
export const GET_USER_FOLLOWER_SUCCESS = 'GET_USER_FOLLOWER_SUCCESS'
export const GET_USER_FOLLOWER_ERROR = 'GET_USER_FOLLOWER_ERROR'

export const GET_POST_DETAILS_REQUEST = 'GET_POST_DETAILS_REQUEST'
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS'
export const GET_POST_DETAILS_ERROR = 'GET_POST_DETAILS_ERROR'

export const CREATE_POST_COMMENT_REQUEST = 'CREATE_POST_COMMENT_REQUEST'
export const CREATE_POST_COMMENT_SUCCESS = 'CREATE_POST_COMMENT_SUCCESS'
export const CREATE_POST_COMMENT_ERROR = 'CREATE_POST_COMMENT_ERROR'

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR'

export const GET_COMMENTS_COUNT_REQUEST = 'GET_COMMENTS_COUNT_REQUEST'
export const GET_COMMENTS_COUNT_SUCCESS = 'GET_COMMENTS_COUNT_SUCCESS'
export const GET_COMMENTS_COUNT_ERROR = 'GET_COMMENTS_COUNT_ERROR'

export const CREATE_OR_UPDATE_COMMENT_REACTION_REQUEST =
  'CREATE_OR_UPDATE_COMMENT_REACTION_REQUEST'
export const CREATE_OR_UPDATE_COMMENT_REACTION_SUCCESS =
  'CREATE_OR_UPDATE_COMMENT_REACTION_SUCCESS'
export const CREATE_OR_UPDATE_COMMENT_REACTION_ERROR =
  'CREATE_OR_UPDATE_COMMENT_REACTION_ERROR'

export const GET_COMMENT_REACTIONS_REQUEST = 'GET_COMMENT_REACTIONS_REQUEST'
export const GET_COMMENT_REACTIONS_SUCCESS = 'GET_COMMENT_REACTIONS_SUCCESS'
export const GET_COMMENT_REACTIONS_ERROR = 'GET_COMMENT_REACTIONS_ERROR'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'
