export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const STORE_USER = 'STORE_USER'
export const AUTH_USER = 'AUTH_USER'
export const USER_LOADING = 'USER_LOADING'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const SAVE_USER_PREFERENCES_REQUEST = 'SAVE_USER_PREFERENCES_REQUEST'
export const SAVE_USER_PREFERENCES_SUCCESS = 'SAVE_USER_PREFERENCES_SUCCESS'
export const SAVE_USER_PREFERENCES_ERROR = 'SAVE_USER_PREFERENCES_ERROR'

export const UPDATE_USER_PREFERENCES_REQUEST = 'UPDATE_USER_PREFERENCES_REQUEST'
export const UPDATE_USER_PREFERENCES_SUCCESS = 'UPDATE_USER_PREFERENCES_SUCCESS'
export const UPDATE_USER_PREFERENCES_ERROR = 'UPDATE_USER_PREFERENCES_ERROR'

export const GET_USER_PREFERENCES_REQUEST = 'GET_USER_PREFERENCES_REQUEST'
export const GET_USER_PREFERENCES_SUCCESS = 'GET_USER_PREFERENCES_SUCCESS'
export const GET_USER_PREFERENCES_ERROR = 'GET_USER_PREFERENCES_ERROR'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const SAVE_FEEDBACK_REQUEST = 'SAVE_FEEDBACK_REQUEST'
export const SAVE_FEEDBACK_SUCCESS = 'SAVE_FEEDBACK_SUCCESS'
export const SAVE_FEEDBACK_ERROR = 'SAVE_FEEDBACK_ERROR'

export const GET_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST'
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS'
export const GET_FEEDBACKS_ERROR = 'GET_FEEDBACKS_ERROR'

export const GET_POSTS_SUMMARY_REQUEST = 'GET_POSTS_SUMMARY_REQUEST'
export const GET_POSTS_SUMMARY_SUCCESS = 'GET_POSTS_SUMMARY_SUCCESS'
export const GET_POSTS_SUMMARY_FAILURE = 'GET_POSTS_SUMMARY_FAILURE'

export const GET_INCOMING_POSTS_REQUEST = 'GET_INCOMING_POSTS_REQUEST'
export const GET_INCOMING_POSTS_SUCCESS = 'GET_INCOMING_POSTS_SUCCESS'
export const GET_INCOMING_POSTS_ERROR = 'GET_INCOMING_POSTS_ERROR'

export const GET_OUTGOING_POSTS_REQUEST = 'GET_OUTGOING_POSTS_REQUEST'
export const GET_OUTGOING_POSTS_SUCCESS = 'GET_OUTGOING_POSTS_SUCCESS'
export const GET_OUTGOING_POSTS_FAILURE = 'GET_OUTGOING_POSTS_FAILURE'

export const GET_NOTIFICATIONS_COUNT_REQUEST = 'GET_NOTIFICATIONS_COUNT_REQUEST'
export const GET_NOTIFICATIONS_COUNT_SUCCESS = 'GET_NOTIFICATIONS_COUNT_SUCCESS'
export const GET_NOTIFICATIONS_COUNT_FAILURE = 'GET_NOTIFICATIONS_COUNT_FAILURE'

export const CREATE_OR_UPDATE_REACTION_REQUEST =
  'CREATE_OR_UPDATE_REACTION_REQUEST'
export const CREATE_OR_UPDATE_REACTION_SUCCESS =
  'CREATE_OR_UPDATE_REACTION_SUCCESS'
export const CREATE_OR_UPDATE_REACTION_FAILURE =
  'CREATE_OR_UPDATE_REACTION_FAILURE'

export const GET_REACTIONS_REQUEST = 'GET_REACTIONS_REQUEST'
export const GET_REACTIONS_SUCCESS = 'GET_REACTIONS_SUCCESS'
export const GET_REACTIONS_ERROR = 'GET_REACTIONS_ERROR'

export const CREATE_OR_UPDATE_PROFILE_REACTION_REQUEST =
  'CREATE_OR_UPDATE_PROFILE_REACTION_REQUEST'
export const CREATE_OR_UPDATE_PROFILE_REACTION_SUCCESS =
  'CREATE_OR_UPDATE_PROFILE_REACTION_SUCCESS'
export const CREATE_OR_UPDATE_PROFILE_REACTION_FAILURE =
  'CREATE_OR_UPDATE_PROFILE_REACTION_FAILURE'

export const GET_USER_LIKE_REQUEST = 'GET_USER_LIKE_REQUEST'
export const GET_USER_LIKE_SUCCESS = 'GET_USER_LIKE_SUCCESS'
export const GET_USER_LIKE_FAILURE = 'GET_USER_LIKE_FAILURE'

export const GET_RECENT_POSTS_REQUEST = 'GET_RECENT_POSTS_REQUEST'
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS'
export const GET_RECENT_POSTS_FAILURE = 'GET_RECENT_POSTS_FAILURE'
