export const GET_REGIONS_REQUEST = 'GET_REGIONS_REQUEST'
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS'
export const GET_REGIONS_ERROR = 'GET_REGIONS_ERROR'

export const CREATE_OR_UPDATE_COUNTRY_REACTION_REQUEST =
  'CREATE_OR_UPDATE_COUNTRY_REACTION_REQUEST'
export const CREATE_OR_UPDATE_COUNTRY_REACTION_SUCCESS =
  'CREATE_OR_UPDATE_COUNTRY_REACTION_SUCCESS'
export const CREATE_OR_UPDATE_COUNTRY_REACTION_ERROR =
  'CREATE_OR_UPDATE_COUNTRY_REACTIONS_ERROR'
