export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_FAILURE = 'GET_USER_POSTS_FAILURE';

export const UPDATE_LIKES_REQUEST = 'UPDATE_LIKES_REQUEST';
export const UPDATE_LIKES_SUCCESS = 'UPDATE_LIKES_SUCCESS';
export const UPDATE_LIKES_FAILURE = 'UPDATE_LIKES_FAILURE';

export const UPDATE_DIS_LIKES_REQUEST = 'UPDATE_DIS_LIKES_REQUEST';
export const UPDATE_DIS_LIKES_SUCCESS = 'UPDATE_DIS_LIKES_SUCCESS';
export const UPDATE_DIS_LIKES_FAILURE = 'UPDATE_DIS_LIKES_FAILURE';

export const GET_USER_POSTS_SELF_REQUEST = 'GET_USER_POSTS_SELF_REQUEST';
export const GET_USER_POSTS_SELF_SUCCESS = 'GET_USER_POSTS_SELF_SUCCESS';
export const GET_USER_POSTS_SELF_FAILURE = 'GET_USER_POSTS_SELF_FAILURE';