export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST'
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS'
export const GET_USER_POSTS_ERROR = 'GET_USER_POSTS_ERROR'

export const UPDATE_LIKES_REQUEST = 'UPDATE_LIKES_REQUEST'
export const UPDATE_LIKES_SUCCESS = 'UPDATE_LIKES_SUCCESS'
export const UPDATE_LIKES_ERROR = 'UPDATE_LIKES_ERROR'

export const UPDATE_DIS_LIKES_REQUEST = 'UPDATE_DIS_LIKES_REQUEST'
export const UPDATE_DIS_LIKES_SUCCESS = 'UPDATE_DIS_LIKES_SUCCESS'
export const UPDATE_DIS_LIKES_ERROR = 'UPDATE_DIS_LIKES_ERROR'

export const GET_OUTGOING_POSTS_REQUEST = 'GET_OUTGOING_POSTS_REQUEST'
export const GET_OUTGOING_POSTS_SUCCESS = 'GET_OUTGOING_POSTS_SUCCESS'
export const GET_OUTGOING_POSTS_ERROR = 'GET_OUTGOING_POSTS_ERROR'
